package com.gcs.rms.pojo;

// Generated Mar 7, 2014 3:40:16 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CandidateSkill generated by hbm2java
 */
@Entity
@Table(name = "candidate_skill", catalog = "rmsdb")
public class CandidateSkill implements java.io.Serializable {

    private Integer candidateSkillId;

    private Skill skill;

    private Candidate candidate;

    public CandidateSkill() {
    }

    public CandidateSkill(Skill skill, Candidate candidate) {
        this.skill = skill;
        this.candidate = candidate;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "Candidate_Skill_ID", unique = true, nullable = false)
    public Integer getCandidateSkillId() {
        return this.candidateSkillId;
    }

    public void setCandidateSkillId(Integer candidateSkillId) {
        this.candidateSkillId = candidateSkillId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "Skill_ID")
    public Skill getSkill() {
        return this.skill;
    }

    public void setSkill(Skill skill) {
        this.skill = skill;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "Candidate_ID")
    public Candidate getCandidate() {
        return this.candidate;
    }

    public void setCandidate(Candidate candidate) {
        this.candidate = candidate;
    }

}
