package com.gcs.rms.pojo;

// Generated Mar 7, 2014 3:40:16 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * CandidateApplication generated by hbm2java
 */
@Entity
@Table(name = "candidate_application", catalog = "rmsdb")
public class CandidateApplication implements java.io.Serializable {

    private Integer candidateId;

    private Application application;

    private ScheduleInterview scheduleInterview;

    private ApplicationPhaseStatus applicationPhaseStatus;

    private ScheduleOnlineTest scheduleOnlineTest;

    private OfferSalary offerSalary;

    private Candidate candidate;

    private String assessmentFile;

    private String onlineTestResult;

    private Set<History> histories = new HashSet<History>(0);

    public CandidateApplication() {
    }

    public CandidateApplication(ApplicationPhaseStatus applicationPhaseStatus, Candidate candidate) {
        this.applicationPhaseStatus = applicationPhaseStatus;
        this.candidate = candidate;
    }

    public CandidateApplication(Application application, ScheduleInterview scheduleInterview,
            ApplicationPhaseStatus applicationPhaseStatus, ScheduleOnlineTest scheduleOnlineTest,
            OfferSalary offerSalary, Candidate candidate, String assessmentFile, String onlineTestResult,
            Set<History> histories) {
        this.application = application;
        this.scheduleInterview = scheduleInterview;
        this.applicationPhaseStatus = applicationPhaseStatus;
        this.scheduleOnlineTest = scheduleOnlineTest;
        this.offerSalary = offerSalary;
        this.candidate = candidate;
        this.assessmentFile = assessmentFile;
        this.onlineTestResult = onlineTestResult;
        this.histories = histories;
    }

    @GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "candidate"))
    @Id
    @GeneratedValue(generator = "generator")
    @Column(name = "Candidate_ID", unique = true, nullable = false)
    public Integer getCandidateId() {
        return this.candidateId;
    }

    public void setCandidateId(Integer candidateId) {
        this.candidateId = candidateId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "Application_ID")
    public Application getApplication() {
        return this.application;
    }

    public void setApplication(Application application) {
        this.application = application;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "Schedule_Interview_ID")
    public ScheduleInterview getScheduleInterview() {
        return this.scheduleInterview;
    }

    public void setScheduleInterview(ScheduleInterview scheduleInterview) {
        this.scheduleInterview = scheduleInterview;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "Application_Phase_Status_ID", nullable = false)
    public ApplicationPhaseStatus getApplicationPhaseStatus() {
        return this.applicationPhaseStatus;
    }

    public void setApplicationPhaseStatus(ApplicationPhaseStatus applicationPhaseStatus) {
        this.applicationPhaseStatus = applicationPhaseStatus;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "Schedule_Online_Test_ID")
    public ScheduleOnlineTest getScheduleOnlineTest() {
        return this.scheduleOnlineTest;
    }

    public void setScheduleOnlineTest(ScheduleOnlineTest scheduleOnlineTest) {
        this.scheduleOnlineTest = scheduleOnlineTest;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "Offer_Salary_ID")
    public OfferSalary getOfferSalary() {
        return this.offerSalary;
    }

    public void setOfferSalary(OfferSalary offerSalary) {
        this.offerSalary = offerSalary;
    }

    @OneToOne(fetch = FetchType.LAZY)
    @PrimaryKeyJoinColumn
    public Candidate getCandidate() {
        return this.candidate;
    }

    public void setCandidate(Candidate candidate) {
        this.candidate = candidate;
    }

    @Column(name = "Assessment_File", length = 50)
    public String getAssessmentFile() {
        return this.assessmentFile;
    }

    public void setAssessmentFile(String assessmentFile) {
        this.assessmentFile = assessmentFile;
    }

    @Column(name = "OnlineTest_Result", length = 50)
    public String getOnlineTestResult() {
        return this.onlineTestResult;
    }

    public void setOnlineTestResult(String onlineTestResult) {
        this.onlineTestResult = onlineTestResult;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "candidateApplication")
    public Set<History> getHistories() {
        return this.histories;
    }

    public void setHistories(Set<History> histories) {
        this.histories = histories;
    }

}
