package com.gcs.rms.pojo;

// Generated Mar 7, 2014 3:40:16 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Division generated by hbm2java
 */
@Entity
@Table(name = "division", catalog = "rmsdb")
public class Division implements java.io.Serializable {

    private Integer divisionId;

    private String divisionName;

    private String location;

    private Set<Vacancy> vacancies = new HashSet<Vacancy>(0);

    public Division() {
    }

    public Division(String divisionName, String location, Set<Vacancy> vacancies) {
        this.divisionName = divisionName;
        this.location = location;
        this.vacancies = vacancies;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "Division_ID", unique = true, nullable = false)
    public Integer getDivisionId() {
        return this.divisionId;
    }

    public void setDivisionId(Integer divisionId) {
        this.divisionId = divisionId;
    }

    @Column(name = "Division_Name", length = 50)
    public String getDivisionName() {
        return this.divisionName;
    }

    public void setDivisionName(String divisionName) {
        this.divisionName = divisionName;
    }

    @Column(name = "Location", length = 50)
    public String getLocation() {
        return this.location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "division")
    public Set<Vacancy> getVacancies() {
        return this.vacancies;
    }

    public void setVacancies(Set<Vacancy> vacancies) {
        this.vacancies = vacancies;
    }

}
