package com.gcs.rms.pojo;

// Generated Mar 7, 2014 3:40:16 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EducationCertificate generated by hbm2java
 */
@Entity
@Table(name = "education_certificate", catalog = "rmsdb")
public class EducationCertificate implements java.io.Serializable {

    private Integer educationCertificateId;

    private School school;

    private Candidate candidate;

    private String certificate;

    private Date startDate;

    private Date endDate;

    public EducationCertificate() {
    }

    public EducationCertificate(School school, Candidate candidate, String certificate, Date startDate, Date endDate) {
        this.school = school;
        this.candidate = candidate;
        this.certificate = certificate;
        this.startDate = startDate;
        this.endDate = endDate;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "Education_Certificate_ID", unique = true, nullable = false)
    public Integer getEducationCertificateId() {
        return this.educationCertificateId;
    }

    public void setEducationCertificateId(Integer educationCertificateId) {
        this.educationCertificateId = educationCertificateId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "School_ID")
    public School getSchool() {
        return this.school;
    }

    public void setSchool(School school) {
        this.school = school;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "Candidate_ID")
    public Candidate getCandidate() {
        return this.candidate;
    }

    public void setCandidate(Candidate candidate) {
        this.candidate = candidate;
    }

    @Column(name = "Certificate", length = 50)
    public String getCertificate() {
        return this.certificate;
    }

    public void setCertificate(String certificate) {
        this.certificate = certificate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "Start_Date", length = 19)
    public Date getStartDate() {
        return this.startDate;
    }

    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "End_Date", length = 19)
    public Date getEndDate() {
        return this.endDate;
    }

    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

}
