package com.gcs.rms.pojo;

// Generated Mar 7, 2014 3:40:16 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * History generated by hbm2java
 */
@Entity
@Table(name = "history", catalog = "rmsdb")
public class History implements java.io.Serializable {

    private Integer historyId;

    private User user;

    private Icon icon;

    private ReasonPhase reasonPhase;

    private CandidateApplication candidateApplication;

    private Date time;

    private String action;

    private String comment;

    public History() {
    }

    public History(User user, Icon icon, ReasonPhase reasonPhase, CandidateApplication candidateApplication, Date time,
            String action, String comment) {
        this.user = user;
        this.icon = icon;
        this.reasonPhase = reasonPhase;
        this.candidateApplication = candidateApplication;
        this.time = time;
        this.action = action;
        this.comment = comment;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "History_ID", unique = true, nullable = false)
    public Integer getHistoryId() {
        return this.historyId;
    }

    public void setHistoryId(Integer historyId) {
        this.historyId = historyId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "User_ID")
    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "Icon_ID")
    public Icon getIcon() {
        return this.icon;
    }

    public void setIcon(Icon icon) {
        this.icon = icon;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "Reason_Phase_ID")
    public ReasonPhase getReasonPhase() {
        return this.reasonPhase;
    }

    public void setReasonPhase(ReasonPhase reasonPhase) {
        this.reasonPhase = reasonPhase;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "Candidate_ID")
    public CandidateApplication getCandidateApplication() {
        return this.candidateApplication;
    }

    public void setCandidateApplication(CandidateApplication candidateApplication) {
        this.candidateApplication = candidateApplication;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "Time", length = 19)
    public Date getTime() {
        return this.time;
    }

    public void setTime(Date time) {
        this.time = time;
    }

    @Column(name = "Action", length = 50)
    public String getAction() {
        return this.action;
    }

    public void setAction(String action) {
        this.action = action;
    }

    @Column(name = "Comment", length = 1000)
    public String getComment() {
        return this.comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

}
