package com.gcs.rms.pojo;

// Generated Mar 7, 2014 3:40:16 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Icon generated by hbm2java
 */
@Entity
@Table(name = "icon", catalog = "rmsdb")
public class Icon implements java.io.Serializable {

    private Integer iconId;

    private String path;

    private String description;

    private Set<History> histories = new HashSet<History>(0);

    public Icon() {
    }

    public Icon(String path, String description, Set<History> histories) {
        this.path = path;
        this.description = description;
        this.histories = histories;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "Icon_ID", unique = true, nullable = false)
    public Integer getIconId() {
        return this.iconId;
    }

    public void setIconId(Integer iconId) {
        this.iconId = iconId;
    }

    @Column(name = "Path", length = 50)
    public String getPath() {
        return this.path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    @Column(name = "Description", length = 1000)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "icon")
    public Set<History> getHistories() {
        return this.histories;
    }

    public void setHistories(Set<History> histories) {
        this.histories = histories;
    }

}
