package com.gcs.rms.pojo;

// Generated Mar 7, 2014 3:40:16 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * OfferSalary generated by hbm2java
 */
@Entity
@Table(name = "offer_salary", catalog = "rmsdb")
public class OfferSalary implements java.io.Serializable {

    private Integer offerSalaryId;

    private Float expectedSalary;

    private Float offerSalary;

    private Set<CandidateApplication> candidateApplications = new HashSet<CandidateApplication>(0);

    public OfferSalary() {
    }

    public OfferSalary(Float expectedSalary, Float offerSalary, Set<CandidateApplication> candidateApplications) {
        this.expectedSalary = expectedSalary;
        this.offerSalary = offerSalary;
        this.candidateApplications = candidateApplications;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "Offer_Salary_ID", unique = true, nullable = false)
    public Integer getOfferSalaryId() {
        return this.offerSalaryId;
    }

    public void setOfferSalaryId(Integer offerSalaryId) {
        this.offerSalaryId = offerSalaryId;
    }

    @Column(name = "Expected_Salary", precision = 12, scale = 0)
    public Float getExpectedSalary() {
        return this.expectedSalary;
    }

    public void setExpectedSalary(Float expectedSalary) {
        this.expectedSalary = expectedSalary;
    }

    @Column(name = "Offer_Salary", precision = 12, scale = 0)
    public Float getOfferSalary() {
        return this.offerSalary;
    }

    public void setOfferSalary(Float offerSalary) {
        this.offerSalary = offerSalary;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "offerSalary")
    public Set<CandidateApplication> getCandidateApplications() {
        return this.candidateApplications;
    }

    public void setCandidateApplications(Set<CandidateApplication> candidateApplications) {
        this.candidateApplications = candidateApplications;
    }

}
