package com.gcs.rms.pojo;

// Generated Mar 7, 2014 3:40:16 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Phase generated by hbm2java
 */
@Entity
@Table(name = "phase", catalog = "rmsdb")
public class Phase implements java.io.Serializable {

    private Integer phaseId;

    private String phaseName;

    private String description;

    private Set<ReasonPhase> reasonPhases = new HashSet<ReasonPhase>(0);

    private Set<Application> applications = new HashSet<Application>(0);

    private Set<ApplicationPhaseStatus> applicationPhaseStatuses = new HashSet<ApplicationPhaseStatus>(0);

    public Phase() {
    }

    public Phase(String phaseName, String description, Set<ReasonPhase> reasonPhases, Set<Application> applications,
            Set<ApplicationPhaseStatus> applicationPhaseStatuses) {
        this.phaseName = phaseName;
        this.description = description;
        this.reasonPhases = reasonPhases;
        this.applications = applications;
        this.applicationPhaseStatuses = applicationPhaseStatuses;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "Phase_ID", unique = true, nullable = false)
    public Integer getPhaseId() {
        return this.phaseId;
    }

    public void setPhaseId(Integer phaseId) {
        this.phaseId = phaseId;
    }

    @Column(name = "Phase_Name", length = 50)
    public String getPhaseName() {
        return this.phaseName;
    }

    public void setPhaseName(String phaseName) {
        this.phaseName = phaseName;
    }

    @Column(name = "Description", length = 50)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "phase")
    public Set<ReasonPhase> getReasonPhases() {
        return this.reasonPhases;
    }

    public void setReasonPhases(Set<ReasonPhase> reasonPhases) {
        this.reasonPhases = reasonPhases;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "phase")
    public Set<Application> getApplications() {
        return this.applications;
    }

    public void setApplications(Set<Application> applications) {
        this.applications = applications;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "phase")
    public Set<ApplicationPhaseStatus> getApplicationPhaseStatuses() {
        return this.applicationPhaseStatuses;
    }

    public void setApplicationPhaseStatuses(Set<ApplicationPhaseStatus> applicationPhaseStatuses) {
        this.applicationPhaseStatuses = applicationPhaseStatuses;
    }

}
