package com.gcs.rms.pojo;

// Generated Mar 7, 2014 3:40:16 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Position generated by hbm2java
 */
@Entity
@Table(name = "position", catalog = "rmsdb")
public class Position implements java.io.Serializable {

    private Integer positionId;

    private Status status;

    private String positionName;

    private String yearOfExperience;

    private String description;

    private Set<Vacancy> vacancies = new HashSet<Vacancy>(0);

    private Set<PositionSkill> positionSkills = new HashSet<PositionSkill>(0);

    private Set<Candidate> candidates = new HashSet<Candidate>(0);

    public Position() {
    }

    public Position(Status status) {
        this.status = status;
    }

    public Position(Status status, String positionName, String yearOfExperience, String description,
            Set<Vacancy> vacancies, Set<PositionSkill> positionSkills, Set<Candidate> candidates) {
        this.status = status;
        this.positionName = positionName;
        this.yearOfExperience = yearOfExperience;
        this.description = description;
        this.vacancies = vacancies;
        this.positionSkills = positionSkills;
        this.candidates = candidates;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "Position_ID", unique = true, nullable = false)
    public Integer getPositionId() {
        return this.positionId;
    }

    public void setPositionId(Integer positionId) {
        this.positionId = positionId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "Position_Status_ID", nullable = false)
    public Status getStatus() {
        return this.status;
    }

    public void setStatus(Status status) {
        this.status = status;
    }

    @Column(name = "Position_Name", length = 50)
    public String getPositionName() {
        return this.positionName;
    }

    public void setPositionName(String positionName) {
        this.positionName = positionName;
    }

    @Column(name = "Year_Of_Experience", length = 50)
    public String getYearOfExperience() {
        return this.yearOfExperience;
    }

    public void setYearOfExperience(String yearOfExperience) {
        this.yearOfExperience = yearOfExperience;
    }

    @Column(name = "Description", length = 1000)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "position")
    public Set<Vacancy> getVacancies() {
        return this.vacancies;
    }

    public void setVacancies(Set<Vacancy> vacancies) {
        this.vacancies = vacancies;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "position")
    public Set<PositionSkill> getPositionSkills() {
        return this.positionSkills;
    }

    public void setPositionSkills(Set<PositionSkill> positionSkills) {
        this.positionSkills = positionSkills;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "position")
    public Set<Candidate> getCandidates() {
        return this.candidates;
    }

    public void setCandidates(Set<Candidate> candidates) {
        this.candidates = candidates;
    }

}
