package com.gcs.rms.pojo;

// Generated Mar 7, 2014 3:40:16 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ReasonPhase generated by hbm2java
 */
@Entity
@Table(name = "reason_phase", catalog = "rmsdb")
public class ReasonPhase implements java.io.Serializable {

    private Integer reasonPhaseId;

    private Reason reason;

    private Phase phase;

    private Set<History> histories = new HashSet<History>(0);

    public ReasonPhase() {
    }

    public ReasonPhase(Reason reason, Phase phase, Set<History> histories) {
        this.reason = reason;
        this.phase = phase;
        this.histories = histories;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "Reason_Phase_ID", unique = true, nullable = false)
    public Integer getReasonPhaseId() {
        return this.reasonPhaseId;
    }

    public void setReasonPhaseId(Integer reasonPhaseId) {
        this.reasonPhaseId = reasonPhaseId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "Reason_ID")
    public Reason getReason() {
        return this.reason;
    }

    public void setReason(Reason reason) {
        this.reason = reason;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "Phase_ID")
    public Phase getPhase() {
        return this.phase;
    }

    public void setPhase(Phase phase) {
        this.phase = phase;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "reasonPhase")
    public Set<History> getHistories() {
        return this.histories;
    }

    public void setHistories(Set<History> histories) {
        this.histories = histories;
    }

}
