package com.gcs.rms.pojo;

// Generated Mar 7, 2014 3:40:16 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ScheduleInterview generated by hbm2java
 */
@Entity
@Table(name = "schedule_interview", catalog = "rmsdb")
public class ScheduleInterview implements java.io.Serializable {

    private Integer scheduleInterviewId;

    private Date interviewTime;

    private String comment;

    private Set<ScheduleInterviewInterviewer> scheduleInterviewInterviewers = new HashSet<ScheduleInterviewInterviewer>(
            0);

    private Set<CandidateApplication> candidateApplications = new HashSet<CandidateApplication>(0);

    public ScheduleInterview() {
    }

    public ScheduleInterview(Date interviewTime, String comment,
            Set<ScheduleInterviewInterviewer> scheduleInterviewInterviewers,
            Set<CandidateApplication> candidateApplications) {
        this.interviewTime = interviewTime;
        this.comment = comment;
        this.scheduleInterviewInterviewers = scheduleInterviewInterviewers;
        this.candidateApplications = candidateApplications;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "Schedule_Interview_ID", unique = true, nullable = false)
    public Integer getScheduleInterviewId() {
        return this.scheduleInterviewId;
    }

    public void setScheduleInterviewId(Integer scheduleInterviewId) {
        this.scheduleInterviewId = scheduleInterviewId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "Interview_Time", length = 19)
    public Date getInterviewTime() {
        return this.interviewTime;
    }

    public void setInterviewTime(Date interviewTime) {
        this.interviewTime = interviewTime;
    }

    @Column(name = "Comment", length = 1000)
    public String getComment() {
        return this.comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "scheduleInterview")
    public Set<ScheduleInterviewInterviewer> getScheduleInterviewInterviewers() {
        return this.scheduleInterviewInterviewers;
    }

    public void setScheduleInterviewInterviewers(Set<ScheduleInterviewInterviewer> scheduleInterviewInterviewers) {
        this.scheduleInterviewInterviewers = scheduleInterviewInterviewers;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "scheduleInterview")
    public Set<CandidateApplication> getCandidateApplications() {
        return this.candidateApplications;
    }

    public void setCandidateApplications(Set<CandidateApplication> candidateApplications) {
        this.candidateApplications = candidateApplications;
    }

}
