package com.gcs.rms.pojo;

// Generated Mar 7, 2014 3:40:16 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ScheduleOnlineTest generated by hbm2java
 */
@Entity
@Table(name = "schedule_online_test", catalog = "rmsdb")
public class ScheduleOnlineTest implements java.io.Serializable {

    private Integer scheduleOnlineTestId;

    private TestCourse testCourse;

    private Date testTime;

    private String comment;

    private Set<CandidateApplication> candidateApplications = new HashSet<CandidateApplication>(0);

    public ScheduleOnlineTest() {
    }

    public ScheduleOnlineTest(TestCourse testCourse, Date testTime, String comment,
            Set<CandidateApplication> candidateApplications) {
        this.testCourse = testCourse;
        this.testTime = testTime;
        this.comment = comment;
        this.candidateApplications = candidateApplications;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "Schedule_Online_Test_ID", unique = true, nullable = false)
    public Integer getScheduleOnlineTestId() {
        return this.scheduleOnlineTestId;
    }

    public void setScheduleOnlineTestId(Integer scheduleOnlineTestId) {
        this.scheduleOnlineTestId = scheduleOnlineTestId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "Test_Course_ID")
    public TestCourse getTestCourse() {
        return this.testCourse;
    }

    public void setTestCourse(TestCourse testCourse) {
        this.testCourse = testCourse;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "Test_Time", length = 19)
    public Date getTestTime() {
        return this.testTime;
    }

    public void setTestTime(Date testTime) {
        this.testTime = testTime;
    }

    @Column(name = "Comment", length = 1000)
    public String getComment() {
        return this.comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "scheduleOnlineTest")
    public Set<CandidateApplication> getCandidateApplications() {
        return this.candidateApplications;
    }

    public void setCandidateApplications(Set<CandidateApplication> candidateApplications) {
        this.candidateApplications = candidateApplications;
    }

}
