package com.gcs.rms.pojo;

// Generated Mar 7, 2014 3:40:16 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Skill generated by hbm2java
 */
@Entity
@Table(name = "skill", catalog = "rmsdb")
public class Skill implements java.io.Serializable {

    private Integer skillId;

    private SkillLevel skillLevel;

    private SkillMaster skillMaster;

    private Set<VacancySkill> vacancySkills = new HashSet<VacancySkill>(0);

    private Set<PositionSkill> positionSkills = new HashSet<PositionSkill>(0);

    private Set<CandidateSkill> candidateSkills = new HashSet<CandidateSkill>(0);

    public Skill() {
    }

    public Skill(SkillLevel skillLevel, SkillMaster skillMaster, Set<VacancySkill> vacancySkills,
            Set<PositionSkill> positionSkills, Set<CandidateSkill> candidateSkills) {
        this.skillLevel = skillLevel;
        this.skillMaster = skillMaster;
        this.vacancySkills = vacancySkills;
        this.positionSkills = positionSkills;
        this.candidateSkills = candidateSkills;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "Skill_ID", unique = true, nullable = false)
    public Integer getSkillId() {
        return this.skillId;
    }

    public void setSkillId(Integer skillId) {
        this.skillId = skillId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "Skill_Level_ID")
    public SkillLevel getSkillLevel() {
        return this.skillLevel;
    }

    public void setSkillLevel(SkillLevel skillLevel) {
        this.skillLevel = skillLevel;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "Skill_Master_ID")
    public SkillMaster getSkillMaster() {
        return this.skillMaster;
    }

    public void setSkillMaster(SkillMaster skillMaster) {
        this.skillMaster = skillMaster;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "skill")
    public Set<VacancySkill> getVacancySkills() {
        return this.vacancySkills;
    }

    public void setVacancySkills(Set<VacancySkill> vacancySkills) {
        this.vacancySkills = vacancySkills;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "skill")
    public Set<PositionSkill> getPositionSkills() {
        return this.positionSkills;
    }

    public void setPositionSkills(Set<PositionSkill> positionSkills) {
        this.positionSkills = positionSkills;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "skill")
    public Set<CandidateSkill> getCandidateSkills() {
        return this.candidateSkills;
    }

    public void setCandidateSkills(Set<CandidateSkill> candidateSkills) {
        this.candidateSkills = candidateSkills;
    }

}
