package com.gcs.rms.pojo;

// Generated Mar 7, 2014 3:40:16 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SkillMaster generated by hbm2java
 */
@Entity
@Table(name = "skill_master", catalog = "rmsdb")
public class SkillMaster implements java.io.Serializable {

    private Integer skillMasterId;

    private SkillCategory skillCategory;

    private String skillMasterName;

    private Set<Skill> skills = new HashSet<Skill>(0);

    public SkillMaster() {
    }

    public SkillMaster(SkillCategory skillCategory, String skillMasterName, Set<Skill> skills) {
        this.skillCategory = skillCategory;
        this.skillMasterName = skillMasterName;
        this.skills = skills;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "Skill_Master_ID", unique = true, nullable = false)
    public Integer getSkillMasterId() {
        return this.skillMasterId;
    }

    public void setSkillMasterId(Integer skillMasterId) {
        this.skillMasterId = skillMasterId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "Skill_Category_ID")
    public SkillCategory getSkillCategory() {
        return this.skillCategory;
    }

    public void setSkillCategory(SkillCategory skillCategory) {
        this.skillCategory = skillCategory;
    }

    @Column(name = "Skill_Master_Name", length = 50)
    public String getSkillMasterName() {
        return this.skillMasterName;
    }

    public void setSkillMasterName(String skillMasterName) {
        this.skillMasterName = skillMasterName;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "skillMaster")
    public Set<Skill> getSkills() {
        return this.skills;
    }

    public void setSkills(Set<Skill> skills) {
        this.skills = skills;
    }

}
