package com.gcs.rms.pojo;

// Generated Mar 7, 2014 3:40:16 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TestCourse generated by hbm2java
 */
@Entity
@Table(name = "test_course", catalog = "rmsdb")
public class TestCourse implements java.io.Serializable {

    private Integer testCourseId;

    private String testCourseName;

    private String description;

    private Set<ScheduleOnlineTest> scheduleOnlineTests = new HashSet<ScheduleOnlineTest>(0);

    public TestCourse() {
    }

    public TestCourse(String testCourseName, String description, Set<ScheduleOnlineTest> scheduleOnlineTests) {
        this.testCourseName = testCourseName;
        this.description = description;
        this.scheduleOnlineTests = scheduleOnlineTests;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "Test_Course_ID", unique = true, nullable = false)
    public Integer getTestCourseId() {
        return this.testCourseId;
    }

    public void setTestCourseId(Integer testCourseId) {
        this.testCourseId = testCourseId;
    }

    @Column(name = "Test_Course_Name", length = 50)
    public String getTestCourseName() {
        return this.testCourseName;
    }

    public void setTestCourseName(String testCourseName) {
        this.testCourseName = testCourseName;
    }

    @Column(name = "Description", length = 1000)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "testCourse")
    public Set<ScheduleOnlineTest> getScheduleOnlineTests() {
        return this.scheduleOnlineTests;
    }

    public void setScheduleOnlineTests(Set<ScheduleOnlineTest> scheduleOnlineTests) {
        this.scheduleOnlineTests = scheduleOnlineTests;
    }

}
