package com.gcs.rms.pojo;

// Generated Mar 7, 2014 3:40:16 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "rmsdb")
public class User implements java.io.Serializable {

    private Integer userId;

    private String userName;

    private String password;

    private String phone;

    private String email;

    private String picture;

    private Set<History> histories = new HashSet<History>(0);

    public User() {
    }

    public User(String userName, String password, String phone, String email, String picture, Set<History> histories) {
        this.userName = userName;
        this.password = password;
        this.phone = phone;
        this.email = email;
        this.picture = picture;
        this.histories = histories;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "User_ID", unique = true, nullable = false)
    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    @Column(name = "User_Name", length = 50)
    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    @Column(name = "Password", length = 50)
    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @Column(name = "Phone", length = 50)
    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    @Column(name = "Email", length = 50)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Column(name = "Picture", length = 50)
    public String getPicture() {
        return this.picture;
    }

    public void setPicture(String picture) {
        this.picture = picture;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
    public Set<History> getHistories() {
        return this.histories;
    }

    public void setHistories(Set<History> histories) {
        this.histories = histories;
    }

}
