package com.gcs.rms.pojo;

// Generated Mar 7, 2014 3:40:16 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VacancySkill generated by hbm2java
 */
@Entity
@Table(name = "vacancy_skill", catalog = "rmsdb")
public class VacancySkill implements java.io.Serializable {

    private Integer vacancySkillId;

    private Skill skill;

    private Vacancy vacancy;

    public VacancySkill() {
    }

    public VacancySkill(Skill skill, Vacancy vacancy) {
        this.skill = skill;
        this.vacancy = vacancy;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "Vacancy_Skill_ID", unique = true, nullable = false)
    public Integer getVacancySkillId() {
        return this.vacancySkillId;
    }

    public void setVacancySkillId(Integer vacancySkillId) {
        this.vacancySkillId = vacancySkillId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "Skill_ID")
    public Skill getSkill() {
        return this.skill;
    }

    public void setSkill(Skill skill) {
        this.skill = skill;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "Vacancy_ID")
    public Vacancy getVacancy() {
        return this.vacancy;
    }

    public void setVacancy(Vacancy vacancy) {
        this.vacancy = vacancy;
    }

}
