package com.gcs.rms.pojo;

// Generated Mar 7, 2014 3:40:16 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WorkingExperience generated by hbm2java
 */
@Entity
@Table(name = "working_experience", catalog = "rmsdb")
public class WorkingExperience implements java.io.Serializable {

    private Integer workingExperienceId;

    private Candidate candidate;

    private String position;

    private String company;

    private Date startDate;

    private Date endDate;

    private String description;

    private Boolean isCurrentWorking;

    public WorkingExperience() {
    }

    public WorkingExperience(Candidate candidate, String position, String company, Date startDate, Date endDate,
            String description, Boolean isCurrentWorking) {
        this.candidate = candidate;
        this.position = position;
        this.company = company;
        this.startDate = startDate;
        this.endDate = endDate;
        this.description = description;
        this.isCurrentWorking = isCurrentWorking;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "Working_Experience_ID", unique = true, nullable = false)
    public Integer getWorkingExperienceId() {
        return this.workingExperienceId;
    }

    public void setWorkingExperienceId(Integer workingExperienceId) {
        this.workingExperienceId = workingExperienceId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "Candidate_ID")
    public Candidate getCandidate() {
        return this.candidate;
    }

    public void setCandidate(Candidate candidate) {
        this.candidate = candidate;
    }

    @Column(name = "Position", length = 50)
    public String getPosition() {
        return this.position;
    }

    public void setPosition(String position) {
        this.position = position;
    }

    @Column(name = "Company", length = 50)
    public String getCompany() {
        return this.company;
    }

    public void setCompany(String company) {
        this.company = company;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "Start_Date", length = 19)
    public Date getStartDate() {
        return this.startDate;
    }

    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "End_Date", length = 19)
    public Date getEndDate() {
        return this.endDate;
    }

    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    @Column(name = "Description", length = 1000)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "Is_Current_Working")
    public Boolean getIsCurrentWorking() {
        return this.isCurrentWorking;
    }

    public void setIsCurrentWorking(Boolean isCurrentWorking) {
        this.isCurrentWorking = isCurrentWorking;
    }

}
