package com.gcs.rms.pojo;

// Generated Mar 7, 2014 3:40:16 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * WorkingLocation generated by hbm2java
 */
@Entity
@Table(name = "working_location", catalog = "rmsdb")
public class WorkingLocation implements java.io.Serializable {

    private Integer workingLocationId;

    private Vacancy vacancy;

    private String workingLocationName;

    private String description;

    public WorkingLocation() {
    }

    public WorkingLocation(Vacancy vacancy) {
        this.vacancy = vacancy;
    }

    public WorkingLocation(Vacancy vacancy, String workingLocationName, String description) {
        this.vacancy = vacancy;
        this.workingLocationName = workingLocationName;
        this.description = description;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "Working_Location_ID", unique = true, nullable = false)
    public Integer getWorkingLocationId() {
        return this.workingLocationId;
    }

    public void setWorkingLocationId(Integer workingLocationId) {
        this.workingLocationId = workingLocationId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "VACANCY_Vacancy_ID", nullable = false)
    public Vacancy getVacancy() {
        return this.vacancy;
    }

    public void setVacancy(Vacancy vacancy) {
        this.vacancy = vacancy;
    }

    @Column(name = "Working_Location_Name", length = 100)
    public String getWorkingLocationName() {
        return this.workingLocationName;
    }

    public void setWorkingLocationName(String workingLocationName) {
        this.workingLocationName = workingLocationName;
    }

    @Column(name = "Description", length = 1000)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

}
